### ISSUE TITLE
Figure out how to pass work to search process

### ISSUE THREAD

**Issue by seanag0234** [byu-dml/d3m-ta2#22]

**Comment by seanag0234** [comment]
I think we could use the producer-consumer pattern to pass out work to search processes. We could have a fixed number of worker threads that take work off of a queue. When a search is requested it simply gets added to the queue and a worker thread takes the work and starts searching.

For reference here is a thread safe priority queue:
https://docs.python.org/3.6/library/queue.html#queue.PriorityQueue

**Comment by bjschoenfeld** [comment]
A similar pattern can be used with the experimenter. Perhaps the priority component will be less prominent in the experimenter, but still useful there to. We should definitely reuse everything we can.

**Comment by seanag0234** [comment]
Yeah it definitely makes sense to reuse what code we can
