### ISSUE TITLE
Figure out source of truth for querying about search solutions

### ISSUE THREAD

**Issue by seanag0234** [byu-dml/d3m-ta2#23]
This includes progress of searching and getting the best solution so far

**Comment by seanag0234** [comment]
For now I think the simplest solution is just to use an in memory data structure to store information about search solutions.

It could look something like:

{
    search_id: (search, search_solutions),
    ...
}

Note: Python's dictionary data structure is thread safe

**Comment by seanag0234** [comment]
It makes more sense to just have the search_id point to a search_process class and the search_process class can contain the list of search_solutions
{
search_id: search_process,
...
}

**Comment by seanag0234** [comment]
@jaromrex Does this sound good to you?

**Comment by jaromrex** [comment]
yeah that makes perfect sense to me
